package com.tiger.restful.order.model;

public class TOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ORDER.bid
     *
     * @mbggenerated
     */
    private Integer bid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.id
     *
     * @return the value of T_ORDER.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.id
     *
     * @param id the value for T_ORDER.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.uid
     *
     * @return the value of T_ORDER.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.uid
     *
     * @param uid the value for T_ORDER.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ORDER.bid
     *
     * @return the value of T_ORDER.bid
     *
     * @mbggenerated
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ORDER.bid
     *
     * @param bid the value for T_ORDER.bid
     *
     * @mbggenerated
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }
}